version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - application:/app
      - .conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - public
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - application:/app
      - ./bedrock:/app
    env_file:
      - bedrock/.env
    networks:
      - public
      - private
    depends_on:
      - mariadb

  mariadb:
    image: yobasystems/alpine-mariadb
    volumes:
      - .data/mysql:/var/lib/mysql
      - .conf/mysql/default.cnf:/etc/my.cnf
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=XilbwCd6i2z3Bi0Y
      - MYSQL_ROOT_PASSWORD=eNwzflUlj9OUOwOl
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - private

volumes:
  application:
networks:
  public:
  private:
